SUB_DIR=smartmon-nacos smartmon-gateway smartmon-core smartmon-smartstor \
	smartmon-vhe smartmon-falcon smartmon-injector smartmon-database

all: $(SUB_DIR)
.PHONY: $(SUB_DIR)

$(SUB_DIR):
	@+make -C $@

