server.port: 18080

spring:
  application.name: smartmon-gateway-test
  cloud.nacos.discovery.server-addr: 172.24.8.55:8848
  jackson.serialization.write-dates-as-timestamps: true
  security:
    user:
      name: root
      password: root
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        - id: smartmon-vhe
          uri: lb://smartmon-vhe
          predicates:
            - Path=/vhe/**
        - id: smartmon-core
          uri: lb://smartmon-core
          predicates:
            - Path=/core/**
        - id: smartmon-smartstor
          uri: lb://smartmon-smartstor
          predicates:
            - Path=/smartstor/**
        - id: smartmon-falcon
          uri: lb://smartmon-falcon
          predicates:
            - Path=/falcon/**
