server.port: 15100

spring:
  application.name: smartmon-smartstor
  cloud.nacos.discovery.server-addr: 127.0.0.1:8848
  jackson.serialization.write-dates-as-timestamps: true

mybatis:
  mapper-locations:
    - classpath:mapping/*Mapper.xml
  type-aliases-package: smartmon.smartstor.infra.persistence.entity

smartmon.data:
  sync: true
  smartstor:
    sync: true
    cron: 0/10 * * * * ?
    timeout: 50000

smartmon.api:
  infoName: smartmon-smartstor
  prefix: /smartstor/api/v2

smartmon.datasource:
  standalone: false
  liquibase.changeLog: classpath:db/smartmon-smartstor-changelog.yaml
  liquibase.debug: true
  h2.path: /var/smartmon
  h2.file: smartstor.h2
  mysql.host: 172.24.8.55
  mysql.user: root
  mysql.password: root
  mysql.db: smartmon_smartstor
