server.port: 18081

spring:
  application.name: smartmon-examples
  cloud.nacos.discovery.server-addr: 127.0.0.1:8848
  jackson.serialization.write-dates-as-timestamps: true

dubbo:
  application.name: smartmon-examples-dubbo
  registry.address: nacos://127.0.0.1:8848
  scan.base-packages: smartmon.examples.data
  protocol:
    name: dubbo
    port: -1
    threads: 15

smartmon.api:
  infoName: smartmon-examples
  prefix: /api/v2/examples

smartmon.datasource:
  standalone: true
  liquibase.changeLog: classpath:db/smartmon-example-changelog.yaml
  liquibase.debug: true
  h2.path: /var/smartmon
  h2.file: smartmon-example.h2
  mysql.host: 172.24.8.55
  mysql.user: root
  mysql.password: root
  mysql.db: smartmon_example
