server.port: 15101

spring:
  application.name: smartmon-vhe
  cloud:
    nacos.discovery.server-addr: 127.0.0.1:8848

ribbon.ConnectTimeout: 500000
ribbon.ReadTimeout: 500000

smartmon.api:
  infoName: smartmon-vhe
  prefix: /vhe/api/v2
