server.port: 15000

spring:
  application.name: smartmon-core
  cloud.nacos.discovery.server-addr: 127.0.0.1:8848
  jackson.serialization.write-dates-as-timestamps: true

dubbo:
  application.name: smartmon-core-dubbo
  registry.address: nacos://127.0.0.1:8848
  service.version: 1.0.0
  scan.base-packages: smartmon.core
  protocol:
    name: dubbo
    port: -1
    threads: 10

mapper:
  use-simple-type: true
  enum-as-simple-type: true

smartmon.api:
  infoName: smartmon-core
  prefix: /core/api/v2

smartmon.datasource:
  standalone: false
  liquibase.changeLog: classpath:db/smartmon-core-changelog.yaml
  liquibase.debug: true
  h2.path: /var/smartmon
  h2.file: core.h2
  mysql.host: 127.0.0.1
  mysql.user: root
  mysql.password: root
  mysql.db: smartmon_core

smartmon.repo:
  filename: smartmon.repo
  id: SMARTMON-REPO

smartmon.batch:
  targetFolder: /tmp/smartmon
