server.port: 15102

spring:
  application.name: smartmon-database
  cloud.nacos.discovery.server-addr: 127.0.0.1:8848
  jackson.serialization.write-dates-as-timestamps: true

smartmon.api:
  infoName: smartmon-database
  prefix: /database/api/v2

smartmon.datasource:
  standalone: false
  liquibase.changeLog: classpath:db/smartmon-database-changelog.yaml
  liquibase.debug: true
  h2.path: /var/smartmon
  h2.file: database.h2
  mysql.host: 127.0.0.1
  mysql.user: root
  mysql.password: root
  mysql.db: smartmon_database
